### ISSUE TITLE
Doesn't  work with es6 classes declaration

### ISSUE THREAD

**Issue by xfg** [gobwas/dm.js#47]
I try to use this library, but dm is die with es6 classes style.
Such description
```javascript
module.exports = class {
  constructor() {
   //code
  }
  method() {
    //code
  }
}
```
throws error:
```
TypeError: Class constructor  cannot be invoked without 'new'
    at Factory.extend.newInstanceWithArgs (/home/user/project/node_modules/dm/lib/factory/constructor.js:30:39)
    at Factory.extend.factory (/home/user/project/node_modules/dm/lib/factory/constructor.js:50:28)
    at /home/user/project/node_modules/dm/lib/dm.js:586:32
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Comment by gobwas** [comment]
Hi @xfg!
Yeah, thats because in the default factory there is a [code](https://github.com/gobwas/dm.js/blob/master/lib/factory/constructor.js#L30).

I think it will work fine with some code like this https://github.com/gobwas/dm.js/pull/48/files.
Could you review it, maybe am I missed something?

**Comment by xfg** [comment]
No, it's not work. See my rapid pull request #49 it's work but I don't know how it can affect other code.

**Comment by gobwas** [comment]
@xfg go in the my PR thread =)
